># <center> <font color='red'> CMPE428 - DATA SCIENCE </font> </center>
>## <center> <font color='blue'> Assignment 2 - Data Representation Using Numpy </font>  </center>

Create a NumPy array named as 'myArray' of size 10x10 and fill it with random integers between 0 and 9

In [172]:
import numpy as np
np.random.seed(0)
myArray = np.random.randint(0, 10, size=(10, 10))

print(myArray)

[[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]]


Display the shape of the array

In [173]:
print(myArray.shape)

(10, 10)


Display the sub-matrix having row indices 0,1,2 and column indices 3,4,5

In [174]:
sub_matrix = myArray[0:3, 3:6]
print(sub_matrix)

[[3 7 9]
 [8 1 6]
 [9 4 3]]


Resphape the submatrix above to a row vector

In [175]:
print(sub_matrix.reshape(-1))

[3 7 9 8 1 6 9 4 3]


Sort the elements in myArray row-wise and print the sorted matrix

In [176]:
sorted_array = np.sort(myArray, axis=1)
print(sorted_array)

[[0 2 3 3 3 4 5 5 7 9]
 [1 1 6 6 7 7 7 8 8 8]
 [0 0 3 3 4 5 5 8 9 9]
 [0 1 1 2 3 3 3 3 7 8]
 [0 0 2 2 3 4 7 7 9 9]
 [0 1 4 4 4 5 5 6 8 9]
 [1 1 2 3 6 7 7 8 9 9]
 [0 3 3 4 4 4 4 5 6 9]
 [0 1 3 4 4 4 5 5 7 8]
 [0 0 1 2 2 3 4 5 5 9]]


Create a 1-D array of ones and stack it to myArray vertically

In [177]:
ones_array = np.ones(10, dtype=int)
myArray=np.vstack((myArray, ones_array))
print(myArray)

[[5 0 3 3 7 9 3 5 2 4]
 [7 6 8 8 1 6 7 7 8 1]
 [5 9 8 9 4 3 0 3 5 0]
 [2 3 8 1 3 3 3 7 0 1]
 [9 9 0 4 7 3 2 7 2 0]
 [0 4 5 5 6 8 4 1 4 9]
 [8 1 1 7 9 9 3 6 7 2]
 [0 3 5 9 4 4 6 4 4 3]
 [4 4 8 4 3 7 5 5 0 1]
 [5 9 3 0 5 0 1 2 4 2]
 [1 1 1 1 1 1 1 1 1 1]]


Add 10 to all elements in myArray

In [178]:
myArray+=10
print(myArray)

[[15 10 13 13 17 19 13 15 12 14]
 [17 16 18 18 11 16 17 17 18 11]
 [15 19 18 19 14 13 10 13 15 10]
 [12 13 18 11 13 13 13 17 10 11]
 [19 19 10 14 17 13 12 17 12 10]
 [10 14 15 15 16 18 14 11 14 19]
 [18 11 11 17 19 19 13 16 17 12]
 [10 13 15 19 14 14 16 14 14 13]
 [14 14 18 14 13 17 15 15 10 11]
 [15 19 13 10 15 10 11 12 14 12]
 [11 11 11 11 11 11 11 11 11 11]]


Add the vector [0,1,2,3,4,5,6,7,8,9] to each row

In [179]:
vector = np.array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])
myArray=myArray+vector
print(myArray)

[[15 11 15 16 21 24 19 22 20 23]
 [17 17 20 21 15 21 23 24 26 20]
 [15 20 20 22 18 18 16 20 23 19]
 [12 14 20 14 17 18 19 24 18 20]
 [19 20 12 17 21 18 18 24 20 19]
 [10 15 17 18 20 23 20 18 22 28]
 [18 12 13 20 23 24 19 23 25 21]
 [10 14 17 22 18 19 22 21 22 22]
 [14 15 20 17 17 22 21 22 18 20]
 [15 20 15 13 19 15 17 19 22 21]
 [11 12 13 14 15 16 17 18 19 20]]


Add 0 to all elements in the first row, 1 to second row, ... 10 to the last row

In [180]:
scalars = np.arange(11).reshape(-1, 1)
myArray=myArray+scalars
print(myArray)

[[15 11 15 16 21 24 19 22 20 23]
 [18 18 21 22 16 22 24 25 27 21]
 [17 22 22 24 20 20 18 22 25 21]
 [15 17 23 17 20 21 22 27 21 23]
 [23 24 16 21 25 22 22 28 24 23]
 [15 20 22 23 25 28 25 23 27 33]
 [24 18 19 26 29 30 25 29 31 27]
 [17 21 24 29 25 26 29 28 29 29]
 [22 23 28 25 25 30 29 30 26 28]
 [24 29 24 22 28 24 26 28 31 30]
 [21 22 23 24 25 26 27 28 29 30]]


Replace all elements of myArray above 20 with 0

In [181]:
myArray[myArray>20]=0
print(myArray)

[[15 11 15 16  0  0 19  0 20  0]
 [18 18  0  0 16  0  0  0  0  0]
 [17  0  0  0 20 20 18  0  0  0]
 [15 17  0 17 20  0  0  0  0  0]
 [ 0  0 16  0  0  0  0  0  0  0]
 [15 20  0  0  0  0  0  0  0  0]
 [ 0 18 19  0  0  0  0  0  0  0]
 [17  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


Replace all elements of myArray larger than 15 with their remainders when divided by 15

In [182]:
myArray[myArray>15]=myArray[myArray>15]% 15
print(myArray)

[[15 11 15  1  0  0  4  0  5  0]
 [ 3  3  0  0  1  0  0  0  0  0]
 [ 2  0  0  0  5  5  3  0  0  0]
 [15  2  0  2  5  0  0  0  0  0]
 [ 0  0  1  0  0  0  0  0  0  0]
 [15  5  0  0  0  0  0  0  0  0]
 [ 0  3  4  0  0  0  0  0  0  0]
 [ 2  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]
 [ 0  0  0  0  0  0  0  0  0  0]]


Delete last 4 columns of myArray

In [183]:
myArray=myArray[:, :6]
print(myArray)

[[15 11 15  1  0  0]
 [ 3  3  0  0  1  0]
 [ 2  0  0  0  5  5]
 [15  2  0  2  5  0]
 [ 0  0  1  0  0  0]
 [15  5  0  0  0  0]
 [ 0  3  4  0  0  0]
 [ 2  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]
 [ 0  0  0  0  0  0]]


Delete last 3 rows of myArray

In [184]:
myArray=myArray[:8,:]
print(myArray)

[[15 11 15  1  0  0]
 [ 3  3  0  0  1  0]
 [ 2  0  0  0  5  5]
 [15  2  0  2  5  0]
 [ 0  0  1  0  0  0]
 [15  5  0  0  0  0]
 [ 0  3  4  0  0  0]
 [ 2  0  0  0  0  0]]


Swap the second and third columns

In [185]:
myArray[:, [2, 3]] = myArray[:, [3, 2]]
print(myArray)

[[15 11  1 15  0  0]
 [ 3  3  0  0  1  0]
 [ 2  0  0  0  5  5]
 [15  2  2  0  5  0]
 [ 0  0  0  1  0  0]
 [15  5  0  0  0  0]
 [ 0  3  0  4  0  0]
 [ 2  0  0  0  0  0]]


Compute the sum of each row by multiplying myArray with a column vector of ones and print the results

In [186]:
ones = np.ones((myArray.shape[1], 1))
row_sums = myArray @ ones
print(row_sums)


[[42.]
 [ 7.]
 [12.]
 [24.]
 [ 1.]
 [20.]
 [ 7.]
 [ 2.]]


Split myArray into two matrices, A and B. A is made up of first 4 columns and B includes last 2 columns

In [187]:
A = myArray[:, :4]
B = myArray[:, 4:]
print(A)
print(B)

[[15 11  1 15]
 [ 3  3  0  0]
 [ 2  0  0  0]
 [15  2  2  0]
 [ 0  0  0  1]
 [15  5  0  0]
 [ 0  3  0  4]
 [ 2  0  0  0]]
[[0 0]
 [1 0]
 [5 5]
 [5 0]
 [0 0]
 [0 0]
 [0 0]
 [0 0]]


Merge A and B back to myArray

In [188]:
myArray=np.concatenate((A, B), axis=1)
print(myArray)

[[15 11  1 15  0  0]
 [ 3  3  0  0  1  0]
 [ 2  0  0  0  5  5]
 [15  2  2  0  5  0]
 [ 0  0  0  1  0  0]
 [15  5  0  0  0  0]
 [ 0  3  0  4  0  0]
 [ 2  0  0  0  0  0]]


Normalize myArray so that each column is of zero mean and unit variance. Print the mean and variances of all columns to check for correctness

In [190]:
means = np.mean(myArray, axis=0)
stds = np.std(myArray, axis=0)
stds = np.where(stds == 0, 1, stds)
myArray = (myArray - means) / stds
print(myArray)
print(np.mean(myArray, axis = 0))
print(np.std (myArray, axis = 0))

[[ 1.27779825e+00  2.30940108e+00  8.98026510e-01  2.55155182e+00
  -6.49309470e-01 -3.77964473e-01]
 [-5.26152220e-01 -1.38777878e-17 -5.38815906e-01 -5.10310363e-01
  -1.77084401e-01 -3.77964473e-01]
 [-6.76481425e-01 -8.66025404e-01 -5.38815906e-01 -5.10310363e-01
   1.71181587e+00  2.64575131e+00]
 [ 1.27779825e+00 -2.88675135e-01  2.33486893e+00 -5.10310363e-01
   1.71181587e+00 -3.77964473e-01]
 [-9.77139836e-01 -8.66025404e-01 -5.38815906e-01 -3.06186218e-01
  -6.49309470e-01 -3.77964473e-01]
 [ 1.27779825e+00  5.77350269e-01 -5.38815906e-01 -5.10310363e-01
  -6.49309470e-01 -3.77964473e-01]
 [-9.77139836e-01 -1.38777878e-17 -5.38815906e-01  3.06186218e-01
  -6.49309470e-01 -3.77964473e-01]
 [-6.76481425e-01 -8.66025404e-01 -5.38815906e-01 -5.10310363e-01
  -6.49309470e-01 -3.77964473e-01]]
[ 1.38777878e-17  1.38777878e-17 -5.55111512e-17 -1.38777878e-17
  0.00000000e+00  4.16333634e-17]
[1. 1. 1. 1. 1. 1.]
